name: On Tag

on:
  push:
    tags:
      - '*'

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout
        run: echo "Hello World"
