name: Build and Tag

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_GH }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.0

      - name: Change package.json private to false
        run: |
          sed -i 's/"private": true/"private": false/g' package.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Move package.json to dist
        run: cp package.json ./dist

      - name: Husky Setup
        run: |
          npx husky install
          npx husky add .husky/commit-msg  "npx --no -- commitlint --edit ${1}"

      - name: NPM Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GH }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: Change package.json private to true
        run: |
          sed -i 's/"private": false/"private": true/g' package.json

      - name: Move package.json back to root, override existing
        run: cp package.json ./
