name: Build and Tag

on:
  workflow_dispatch:

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_GH }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.0

      - name: Change package.json private to false
        run: |
          sed -i 's/"private": true/"private": false/g' package.json

      - name: NPM CI and Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GH }}
        run: npm ci && npx semantic-release
