name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ssh-key: '${{ secrets.SSH_KEY }}'
          fetch-depth: 0

      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: go version

      - name: Install release-version
        run: go install github.com/flume/release-version@latest

      #- name: Git Config
      #  run: |-
      #    git config user.name coryjohnson-flume
      #    git config user.email cory.johnson@flumehealth.com

      - name: Check Release
        run: release-version semver

      - name: Create Release
        run: release-version release
