name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - run: go version

      - name: Install release-version
        run: go install github.com/flume/release-version@latest

      - name: Git Config
        run: |-
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Check Release
        run: release-version semver

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: release-version release
